### ISSUE TITLE
 Connection Refused Error Encountered

### ISSUE THREAD

**Issue by 2018211801** [gabrielerossi/peanuts-GAN-generator#1]
Thank you for your hard work on this project. I appreciate your efforts.

While testing the application, I encountered a bug where the connection was refused. Could you please advise on how to resolve this issue?

Specific details:
- Error message: Connection Refused
_Traceback (most recent call last):
  File "/mnt/data/wxc/workspace/project/peanuts_dataset/src/main.py", line 26, in <module>
    urls = scraper.get_asset_urls(comic_urls)
  File "/mnt/data/wxc/workspace/project/peanuts_dataset/src/scraper/scraper.py", line 28, in get_asset_urls
    results = self.scrape_single_threaded(urls, self.get_asset_url)
  File "/mnt/data/wxc/workspace/project/peanuts_dataset/src/scraper/scraper.py", line 88, in scrape_single_threaded
    results.append(handler(url, headers))
  File "/mnt/data/wxc/workspace/project/peanuts_dataset/src/scraper/scraper.py", line 180, in get_asset_url
    response = requests.get(url, headers=headers)
  File "/home/wxc/miniconda3/envs/penuts/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/wxc/miniconda3/envs/penuts/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wxc/miniconda3/envs/penuts/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wxc/miniconda3/envs/penuts/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/wxc/miniconda3/envs/penuts/lib/python3.8/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.gocomics.com', port=443): Max retries exceeded with url: /peanuts/2024/01/01 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe52063b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))_

Any guidance or suggestions on how to troubleshoot this would be greatly appreciated.

Thank you in advance for your assistance.

Would you like me to explain or modify any part of this issue report?

**Comment by 2018211801** [comment]
I have check that curl and ping www.gocomics.com are both failed.
